---

Resources:
  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: DISABLED
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: TestEFS

  # EFSMountTargetSub1:  
  #   Type: AWS::EFS::MountTarget
  #   Properties: 
  #     FileSystemId: !Ref EFSFileSystem
  #     SecurityGroups: 
  #       - !GetAtt EFSSecGroup.GroupId
  #     SubnetId: !Ref Snet1

  # EFSMountTargetSub2:  
  #   Type: AWS::EFS::MountTarget
  #   Properties: 
  #     FileSystemId: !Ref EFSFileSystem
  #     SecurityGroups: 
  #       - !GetAtt EFSSecGroup.GroupId
  #     SubnetId: !Ref Snet2

  # EFSMountTargetSub3:  
  #   Type: AWS::EFS::MountTarget
  #   Properties: 
  #     FileSystemId: !Ref EFSFileSystem
  #     SecurityGroups: 
  #       - !GetAtt EFSSecGroup.GroupId
  #     SubnetId: !Ref Snet3